# ----------------------
# Version: 2025.11.2
# Note: Only for Marstek EMS 153 or higher
# By: WargamingPlayer
# Fork of https://github.com/Superduper1969/MarstekVenus-ElfinEW11
# ----------------------

# ----------------
# TEMPLATE SENSORS
# ----------------
template:
  - sensor:
      - name: "Marstek Charging in W"
        unique_id: marstek_charging_in_w
        unit_of_measurement: W
        device_class: power
        state_class: measurement
        state: >
          {%- set ch1=0 | int %}
          {%- set ch2=0 | int %}
          {%- set ch3=0 | int %}
          {%- if has_value('sensor.marstek_1_charging_in_w') %}
          {%- set ch1= states('sensor.marstek_1_charging_in_w') | int %}
          {%- endif %}
          {%- if has_value('sensor.marstek_2_charging_in_w') %}
          {%- set ch2= states('sensor.marstek_2_charging_in_w') | int %}
          {%- endif %}
          {%- if has_value('sensor.marstek_3_charging_in_w') %}
          {%- set ch3= states('sensor.marstek_3_charging_in_w') | int %}
          {%- endif %}
          {{ (ch1 + ch2 + ch3) | int }}

  - sensor:
      - name: "Marstek Discharging in W"
        unique_id: marstek_discharging_in_w
        unit_of_measurement: W
        device_class: power
        state_class: measurement
        state: >
          {%- set ch1=0 | int %}
          {%- set ch2=0 | int %}
          {%- set ch3=0 | int %}
          {%- if has_value('sensor.marstek_1_discharging_in_w') %}
          {%- set ch1= states('sensor.marstek_1_discharging_in_w') | int %}
          {%- endif %}
          {%- if has_value('sensor.marstek_2_discharging_in_w') %}
          {%- set ch2= states('sensor.marstek_2_discharging_in_w') | int %}
          {%- endif %}
          {%- if has_value('sensor.marstek_3_discharging_in_w') %}
          {%- set ch3= states('sensor.marstek_3_discharging_in_w') | int %}
          {%- endif %}
          {{ (ch1 + ch2 + ch3) | int }}

  - sensor:
      - name: "Marstek Batteries Energy"
        unique_id: marstek_batteries_energy
        unit_of_measurement: Wh
        device_class: energy_storage
        state_class: measurement
        state: >
          {%- set cap1=0 | int %}
          {%- set cap2=0 | int %}
          {%- set cap3=0 | int %}
          {%- if has_value('sensor.marstek_1_battery_energy') %}
          {%- set cap1= states('sensor.marstek_1_battery_energy') | int * 1024 |  int %}
          {%- endif %}
          {%- if has_value('sensor.marstek_2_battery_energy') %}
          {%- set cap2= states('sensor.marstek_2_battery_energy') | int * 1024 |  int %}
          {%- endif %}
          {%- if has_value('sensor.marstek_3_battery_energy') %}
          {%- set cap2= states('sensor.marstek_3_battery_energy') | int * 1024 |  int %}
          {%- endif %}
          {{ cap1 + cap2 + cap3 | int }}

  - sensor:
      - name: "Marstek Batteries Charge"
        unique_id: marstek_batteries_charge
        unit_of_measurement: Wh
        device_class: energy_storage
        state_class: measurement
        state: >
          {%- set cap1=0 | int %}
          {%- set cap2=0 | int %}
          {%- set cap3=0 | int %}
          {%- if has_value('sensor.marstek_1_battery_soc_in_Wh') %}
          {%- set cap1= states('sensor.marstek_1_battery_soc_in_Wh') | int %}
          {%- endif %}
          {%- if has_value('sensor.marstek_2_battery_soc_in_Wh') %}
          {%- set cap2= states('sensor.marstek_2_battery_soc_in_Wh') | int %}
          {%- endif %}
          {%- if has_value('sensor.marstek_3_battery_soc_in_Wh') %}
          {%- set cap3= states('sensor.marstek_3_battery_soc_in_Wh') | int %}
          {%- endif %}
          {%- set total= cap1 + cap2 + cap3 | int %}
          {{ total | round(1) }}

  - sensor:
      - name: "Marstek Batteries SOC"
        unique_id: marstek_batteries_soc
        unit_of_measurement: "%"
        device_class: battery
        state_class: measurement
        state: >
          {%- set totalcap=1 | float(default=1) %}
          {%- set charge=1 | float(default=1) %}
          {%- if has_value('sensor.marstek_batteries_energy') %}
            {%- set totalcap= states('sensor.marstek_batteries_energy') | float(default=0) %}
          {%- endif %}
          {%- if has_value('sensor.marstek_batteries_charge') %}
            {%- set charge= states('sensor.marstek_batteries_charge') | float(default=0) %}
          {%- endif %}
          {{ ((charge / totalcap ) | float(default=0) * 100) | round(1) }}  


  - sensor:
      # Expiremental
      # Calculation does not add up as it should, Tweakers is not correct on this.
      - name: "Marstek Efficiency Percentage"
        unique_id: marstek_efficiency_percentage
        unit_of_measurement: "%"
        state_class: measurement
        state: >
          {%- set charging1 = 0 | float(default=0) %}
          {%- set charging2 = 0 | float(default=0) %}
          {%- set charging3 = 0 | float(default=0) %}
          {%- set discharging1 = 0 | float(default=0) %}
          {%- set discharging2 = 0 | float(default=0) %}
          {%- set discharging3 = 0 | float(default=0) %}
          {%- if has_value('sensor.marstek_1_total_charging_energy') %}
            {%- set charging1 = states('sensor.marstek_1_total_charging_energy') | float(default=0) %}
            {%- set discharging1 = states('sensor.marstek_1_total_discharging_energy') | float(default=0) %}
          {%- endif %}
          {%- if has_value('sensor.marstek_2_total_charging_energy') %}
            {%- set charging2 = states('sensor.marstek_2_total_charging_energy') | float(default=0) %}
            {%- set discharging2 = states('sensor.marstek_2_total_discharging_energy') | float(default=0) %}
          {%- endif %}
          {%- if has_value('sensor.marstek_2_total_charging_energy') %}
            {%- set charging3 = states('sensor.marstek_1_total_charging_energy') | float(default=0) %}
            {%- set discharging3 = states('sensor.marstek_1_total_discharging_energy') | float(default=0) %}
          {%- endif %}
          {% set charging = charging1 + charging2 + charging3 | float(default=0) %}
          {% set discharging = discharging1 + discharging2 + discharging3 | float(default=0) %}
          {% if charging > 0 %}
            {{ ((discharging / charging) * 100) | int }}
          {% else %}
            0
          {% endif %}

# -------
# SENSORS
# -------
sensor:
  - platform: integration
    name: Marstek Discharging in kWh
    unique_id: marstek_discharging_in_kwh
    source: sensor.marstek_discharging_in_w
    round: 2
    unit_prefix: k
    unit_time: h
    method: left
  - platform: integration
    name: Marstek Charging in kWh
    unique_id: marstek_charging_in_kwh
    source: sensor.marstek_charging_in_w
    round: 2
    unit_prefix: k
    unit_time: h
    method: left

# --------------
# UTILITY METERS
# --------------
utility_meter:
  marstek_daily_discharge:
    name: Marstek Daily Discharging in kWh
    unique_id: marstek_daily_discharging_in_kwh
    source: sensor.marstek_discharging_in_kwh
    cycle: daily

  marstek_daily_charge:
    name: Marstek Daily Charging in kWh
    unique_id: marstek_daily_charging_in_kwh
    source: sensor.marstek_charging_in_kwh
    cycle: daily
